name: Release Ubuntu Images
on:
  push:
    branches:
      - master


jobs:
  build_base_image:
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@master
    with:
      image_path: $GITHUB_WORKSPACE/images/ubuntu
      image_tag: default
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_clang_12_image:
    needs: build_base_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@master
    with:
      image_path: $GITHUB_WORKSPACE/images/ubuntu/clang-12
      image_tag: clang-12
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_clang_13_image:
    needs: build_base_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@master
    with:
      image_path: $GITHUB_WORKSPACE/images/ubuntu/clang-13
      image_tag: clang-13
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_gcc_10_image:
    needs: build_clang_13_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@master
    with:
      image_path: $GITHUB_WORKSPACE/images/ubuntu/gcc-10
      image_tag: gcc-10
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_gcc_11_image:
    needs: build_clang_13_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@master
    with:
      image_path: $GITHUB_WORKSPACE/images/ubuntu/gcc-11
      image_tag: gcc-11
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}
