name: Release all images
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login 
        run: docker login yukicpp.jfrog.io -u yuki-bot -p ${{ secrets.ARTIFACTORY_KEY }}
      
      - name: Build and push CI/clang-13
        run: |
          docker build  $GITHUB_WORKSPACElimages/ci/clang-13 -t ubuntu_20_04:clang-13
          docker tag ubuntu_20_04:clang-13 yukicpp.jfrog.io/ci-images/ubuntu_20_04:clang-13
          docker push yukicpp.jfrog.io/ci-images/ubuntu_20_04:clang-13
