name: Release Ubuntu Images
on:
  workflow_dispatch:

jobs:
  build_base_image:
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@generic_ubuntu_base_image
    with:
      image_path: $GITHUB_WORKSPACE/images/ci
      image_tag: default
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_clang_14_image:
    needs: build_base_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@generic_ubuntu_base_image
    with:
      image_path: $GITHUB_WORKSPACE/images/ci/clang-14
      image_tag: clang-14
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_clang_13_image:
    needs: build_base_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@generic_ubuntu_base_image
    with:
      image_path: $GITHUB_WORKSPACE/images/ci/clang-13
      image_tag: clang-13
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}

  build_gcc_11_image:
    needs: build_clang_14_image
    uses: Yuki-cpp/yuki_docker/.github/workflows/build_ubuntu_image.yml@generic_ubuntu_base_image
    with:
      image_path: $GITHUB_WORKSPACE/images/ci/gcc-11
      image_tag: gcc-11
      owner_name: ${{ github.repository_owner }}
      username: ${{ github.actor }}
