name: Release CI image
on:
  workflow_dispatch:

jobs:
  Clang13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          IMAGE_NAME=ubuntu_20_04:clang-13
          docker build $GITHUB_WORKSPACE/images/ci/clang-13 --tag ubuntu_20_04:clang-13 --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository_owner }}/ubuntu_20_04:clang-13 | tr '[A-Z]' '[a-z]')
          docker tag ubuntu_20_04:clang-13 $IMAGE_ID
          docker push $IMAGE_ID
  Clang14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          IMAGE_NAME=ubuntu_20_04:clang-14
          docker build $GITHUB_WORKSPACE/images/ci/clang-14 --tag ubuntu_20_04:clang-14 --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository_owner }}/ubuntu_20_04:clang-14 | tr '[A-Z]' '[a-z]')
          docker tag ubuntu_20_04:clang-14 $IMAGE_ID
          docker push $IMAGE_ID
          
