name: Release CI image
on:
  workflow_dispatch:
    inputs:
        compiler:
          type: choice
          description: Compiler to use
          options: 
          - clang-13
          - clang-14

jobs:
  Clang13:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGE_NAME=ubuntu_20_04:latest
          docker build $GITHUB_WORKSPACE/images/ci/${{ github.event.inputs.compiler }} --tag ubuntu_20_04:latest --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ubuntu_20_04:latest ghcr.io/${{ github.repository_owner }}/ubuntu_20_04:latest
          docker push ghcr.io/${{ github.repository_owner }}/ubuntu_20_04:latest

          